
import './globals.css'
import "./styles/base.css"
import HeaderComponent from "@/components/HeaderComponent"
import FooterComponent from "@/components/FooterComponent"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <HeaderComponent></HeaderComponent>
        <main className="min-h-screen mt-12 bg-background flex flex-col items-center">
          
          {children}
        </main>
      </body>
    </html>
  )
}
export const dynamic = 'force-dynamic'